#:schema node_modules/wrangler/config-schema.json
name = "rin-server"
main = "server/src/_worker.ts"
compatibility_date = "2024-05-29"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[triggers]
crons = ["*/20 * * * *"]

[vars]
FRONTEND_URL = "http://localhost:5173"
S3_FOLDER = "images/"
S3_CACHE_FOLDER="cache/"
S3_REGION = "auto"
S3_ENDPOINT = "<YourS3Endpoint>"
S3_ACCESS_HOST = "<YourS3AccessHost>"
S3_BUCKET = "<YourS3BucketName>"
S3_FORCE_PATH_STYLE = "false"
WEBHOOK_URL = "https://<YourWebhookURL>"
RSS_TITLE = "Samuel的博客"
RSS_DESCRIPTION = "博客用于分析网络工具已经交流讨论使用，请勿用于违法用途，公网信息混乱请个人甄别信息真假，坚决贯彻一个中国原则是每个中国人因有的基本素质！"

[[d1_databases]]
binding = "D8"
database_name = "rin"
database_id = "800ddccc-2616-4b4d-a11e-4db53ea00ed5"
